language: java

sudo: false

addons:
  sonarcloud:
    organization: "qlack"
    token:
      secure: "885590c371afab349e42b258d99b33fed9d8e6d2"

jdk: openjdk8

script: mvn clean install -Pcoverage sonar:sonar

notifications:
  email:
    recipients:
      - qlack@eurodyn.com
    on_success: change
    on_failure: change