version: '3.7'

networks:
  webdesktop_network:
    driver: bridge

services:
  qlack-webdesktop-keycloak:
    image: jboss/keycloak:9.0.2
    volumes:
      - ${KEYCLOAK_EXPORTS_LOCATION}:/opt/jboss/keycloak/imports/
    command:
      - "-b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-db:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: QlackWebDesktop
    ports:
      - "3304:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-applications-management:
    image: eurodyn/qlack-webdesktop-apps-applications-management-app:latest
    environment:
      WEBDESKTOP_PORT: ${WEBDESKTOP_PORT}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-translations-management:
    image: eurodyn/qlack-webdesktop-apps-translations-management-app:latest
    environment:
      WEBDESKTOP_PORT: ${WEBDESKTOP_PORT}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-user-profile-management:
    image: eurodyn/qlack-webdesktop-apps-user-profile-management-app:latest
    environment:
      WEBDESKTOP_PORT: ${WEBDESKTOP_PORT}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-app:
    image: eurodyn/qlack-webdesktop-app:latest
    environment:
      WEBDESKTOP_PORT: ${WEBDESKTOP_PORT}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SYSTEM_DEFAULT_LANGUAGE: ${SYSTEM_DEFAULT_LANGUAGE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      LDAP_ENABLED: ${LDAP_ENABLED}
      LDAP_URL: ${LDAP_URL}
      LDAP_BASEDN: ${LDAP_BASEDN}
      LDAP_MAPPING_UID: ${LDAP_MAPPING_UID}
      LDAP_MAPPING_GID: ${LDAP_MAPPING_GID}
      LDAP_ADMIN_UID: ${LDAP_ADMIN_UID}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
      WEBDESKTOP_ADMIN: ${WEBDESKTOP_ADMIN}
      APPS_URL: ${APPS_URL}
    ports:
      - "${WEBDESKTOP_PORT}:${WEBDESKTOP_PORT}"
    restart: always
    networks:
      - webdesktop_network