version: '3.7'

networks:
  qlack-webdesktop-network:
    driver: bridge

services:
  qlack-webdesktop-nginx:
    image: nginx:1.19.5-alpine
    container_name: qlack-webdesktop-nginx
    restart: unless-stopped
    volumes:
      - ./docker-data/nginx:/etc/nginx/conf.d
      - ./docker-data/certbot/conf:/etc/letsencrypt
      - ./docker-data/certbot/www:/var/www/certbot
    ports:
      - "${NGNIX_PORT}:${NGNIX_PORT}"
      - "443:443"
    networks:
      - qlack-webdesktop-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  qlack-webdesktop-certbot:
    image: certbot/certbot:v1.9.0
    restart: unless-stopped
    volumes:
      - ./docker-data/certbot/conf:/etc/letsencrypt
      - ./docker-data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  qlack-webdesktop-keycloak:
    image: jboss/keycloak:11.0.3
    container_name: qlack-webdesktop-keycloak
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
    restart: unless-stopped
    volumes:
      - ${KEYCLOAK_THEME_PATH}:/opt/jboss/keycloak/themes/custom-theme
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-db:
    image: mysql:8.0.17
    container_name: qlack-webdesktop-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: QlackWebDesktop
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-applications-management:
    image: eurodyn/qlack-webdesktop-apps-applications-management-app:${WEBDESKTOP_VERSION}
    container_name: qlack-webdesktop-applications-management
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      OAUTH2_CLIENT: ${OAUTH2_CLIENT}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
    restart: unless-stopped
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-translations-management:
    image: eurodyn/qlack-webdesktop-apps-translations-management-app:${WEBDESKTOP_VERSION}
    container_name: qlack-webdesktop-translations-management
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      OAUTH2_CLIENT: ${OAUTH2_CLIENT}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
    restart: unless-stopped
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-user-profile-management:
    image: eurodyn/qlack-webdesktop-apps-user-profile-management-app:${WEBDESKTOP_VERSION}
    container_name: qlack-webdesktop-user-profile-management
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      OAUTH2_CLIENT: ${OAUTH2_CLIENT}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
    restart: unless-stopped
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-app:
    image: eurodyn/qlack-webdesktop-app:${WEBDESKTOP_VERSION}
    container_name: qlack-webdesktop-app
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SYSTEM_DEFAULT_LANGUAGE: ${SYSTEM_DEFAULT_LANGUAGE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      OAUTH2_CLIENT: ${OAUTH2_CLIENT}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      WEBDESKTOP_ADMIN: ${WEBDESKTOP_ADMIN}
      APPS_URL: ${APPS_URL}
    restart: unless-stopped
    ports:
      - "${WEBDESKTOP_PORT}:8082"
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-logs:
    image: amir20/dozzle:v3.0.2
    container_name: qlack-webdesktop-logs
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${LOGS_PORT}:8080"
    networks:
      - qlack-webdesktop-network
