version: '3.7'

networks:
  webdesktop_network:
    driver: bridge

services:
  qlack-webdesktop-keycloak:
    image: jboss/keycloak:9.0.3
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "${KEYCLOAK_PORT}:8080"
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-db:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: QlackWebDesktop
    ports:
      - "3304:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-applications-management:
    image: eurodyn/qlack-webdesktop-apps-applications-management-app:${WEBDESKTOP_VERSION}
    environment:
      WEBDESKTOP_PORT: ${WEBDESKTOP_PORT}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      WEBDESKTOP_SCHEME: ${WEBDESKTOP_SCHEME}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-translations-management:
    image: eurodyn/qlack-webdesktop-apps-translations-management-app:${WEBDESKTOP_VERSION}
    environment:
      WEBDESKTOP_PORT: ${WEBDESKTOP_PORT}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      WEBDESKTOP_SCHEME: ${WEBDESKTOP_SCHEME}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-user-profile-management:
    image: eurodyn/qlack-webdesktop-apps-user-profile-management-app:${WEBDESKTOP_VERSION}
    environment:
      WEBDESKTOP_PORT: ${WEBDESKTOP_PORT}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      WEBDESKTOP_SCHEME: ${WEBDESKTOP_SCHEME}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    restart: always
    networks:
      - webdesktop_network

  qlack-webdesktop-app:
    image: eurodyn/qlack-webdesktop-app:${WEBDESKTOP_VERSION}
    environment:
      WEBDESKTOP_PORT: ${WEBDESKTOP_PORT}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SYSTEM_DEFAULT_LANGUAGE: ${SYSTEM_DEFAULT_LANGUAGE}
      WEBDESKTOP_URL: ${WEBDESKTOP_URL}
      WEBDESKTOP_SCHEME: ${WEBDESKTOP_SCHEME}
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      WEBDESKTOP_ADMIN: ${WEBDESKTOP_ADMIN}
      APPS_URL: ${APPS_URL}
    ports:
      - "${WEBDESKTOP_PORT}:${WEBDESKTOP_PORT}"
    restart: always
    networks:
      - webdesktop_network