version: '3.7'

networks:
  qlack-webdesktop-network:
    driver: bridge

services:
  qlack-webdesktop-db:
    image: mysql:8.0.17
    container_name: qlack-webdesktop-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: QlackWebDesktop
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:3306"
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-applications-management:
    image: eurodyn/qlack-webdesktop-apps-applications-management-app:${WEBDESKTOP_VERSION}
    container_name: qlack-webdesktop-applications-management
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-translations-management:
    image: eurodyn/qlack-webdesktop-apps-translations-management-app:${WEBDESKTOP_VERSION}
    container_name: qlack-webdesktop-translations-management
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-user-profile-management:
    image: eurodyn/qlack-webdesktop-apps-user-profile-management-app:${WEBDESKTOP_VERSION}
    container_name: qlack-webdesktop-user-profile-management
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-app:
    image: eurodyn/qlack-webdesktop-app:${WEBDESKTOP_VERSION}
    container_name: qlack-webdesktop-app
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      SYSTEM_DEFAULT_LANGUAGE: ${SYSTEM_DEFAULT_LANGUAGE}
      APPS_URL: ${APPS_URL}
    restart: unless-stopped
    ports:
      - "${WEBDESKTOP_PORT}:8082"
    networks:
      - qlack-webdesktop-network

  qlack-webdesktop-logs:
    image: amir20/dozzle:v3.0.2
    container_name: qlack-webdesktop-logs
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${LOGS_PORT}:8080"
    networks:
      - qlack-webdesktop-network
