# application configuration
---
appUrl: 'http://localhost:8089'
version: '3.0.0-SNAPSHOT'
icon: 'http://icons.iconarchive.com/icons/franksouza183/fs/64/Categories-preferences-system-icon.png'
iconSmall: 'http://icons.iconarchive.com/icons/franksouza183/fs/24/Categories-preferences-system-icon.png'
width: '800'
minWidth: '470'
height: '500'
minHeight: '450'
active: true
multipleInstances: false
restrictAccess: false
resizable: true
draggable: true
closable: true
minimizable: true
maximizable: true
system: true
showTitle: true
stripPrefix: false
sensitiveHeaders: 'management'
proxyPath: 'http://localhost:8089'
applicationName: management
editedByUI: false
proxyAppUrl: 'http://localhost:8089'
lexicon:
  - languageLocale: en
    values:
      - key: title
        value: Applications/Users Management
      - key: description
        value: System application which manages the users and the applications.
  - languageLocale: el
    values:
      - key: title
        value: Διαχείρηση Εφαρμογών/Χρηστών
      - key: description
        value: Εφαρμογή συστήματος η οποία διαχειρίζεται τους χρήστες και τις εφαρμογές.