# application configuration
---
applicationName: management
groupName: system
appUrl: 'http://localhost:8090'
appPath: "/applicationsManagement/"
icon: "http://localhost:8082/applications/logo/icon"
iconSmall: "http://localhost:8082/applications/logo/icon_small"
width: '800'
minWidth: '470'
height: '500'
minHeight: '450'
active: true
multipleInstances: false
restrictAccess: false
resizable: true
draggable: true
closable: true
minimizable: true
maximizable: true
system: true
showTitle: true
proxyAppUrl: '/applications/'
proxyAppPath: '/applications/**'
version: '3.0.0-SNAPSHOT'
lexicon:
  - languageLocale: en
    values:
      - key: title
        value: Applications/Users Management
      - key: description
        value: System application which manages the users and the applications.
  - languageLocale: el
    values:
      - key: title
        value: Διαχείρηση Εφαρμογών/Χρηστών
      - key: description
        value: Εφαρμογή συστήματος η οποία διαχειρίζεται τους χρήστες και τις εφαρμογές.