---
groups:
  - name: webdesktop-ui
    description: webdesktopUi description
  - name: translations-management-ui
    description: translations management description
  - name: management-app-ui
    description: translations of management applications
languages:
- name: "English"
  locale: "en"
- name: "Ελληνικά"
  locale: "el"
- name: "Deutsch"
  locale: "de"
- name: "Français"
  locale: "fr"

translations:
- group: webdesktop-ui
  locale: en
  keys:
    - groupOthers: Others
    - system: System
- group: webdesktop-ui
  locale: el
  keys:
    - groupOthers: Άλλα
    - system: Σύστημα

- group: translations-management-ui
  locale: en
  keys:
    - languages: Languages
    - translations: Translations
    - copyTranslations: Copy translations
    - cancel: Cancel
    - saveChanges: Save changes
    - groupName: Group Name
    - keyName: Key Name
    - create: Create
    - keyEdit: Key Edit
    - save: Save
    - itemsPerPage: items per page
    - rangeLabel: of
    - changes: Changes
    - saved: Saved!
    - error: Error!
    - errorMessage: Something went wrong
    - inactive-active: Inactive/Active
    - languageCreate: Language create
    - languageName: Language name
    - languageLocale: Language locale
    - none: None
- group: translations-management-ui
  locale: el
  keys:
    - languages: Γλώσσες
    - translations: Μεταφράσεις
    - copyTranslations: Aντιγράψτε μεταφράσεις
    - cancel: Ακύρωση
    - saveChanges: Αποθηκεύστε  τις αλλαγές
    - groupName: Όνομα ομάδας
    - keyName: Όνομα κλειδιού
    - create: Δημιουργία
    - keyEdit: Επεξεργασία κλειδιού
    - save: Αποθήκευση
    - itemsPerPage: αντικείμενα ανά σελίδα
    - rangeLabel: από
    - changes: Οι αλλαγές
    - saved: Αποθηκεύτηκαν
    - error: Σφάλμα!
    - errorMessage: Κάτι πήγε στραβά
    - inactive-active: Ανενεργή/Ενεργή
    - languageCreate: Δημιουργία γλώσσας
    - languageName: Όνομα  γλώσσας
    - languageLocale: Τοπικό γλώσσας
    - none: Καμία
- group: management-app-ui
  locale: en
  keys:
    - header: Applications Management
    - title: Name
    - image: Image
    - description: Description
    - version: Version
    - cancel: Cancel
    - create: Create
    - save: Save
    - pagination: Items per page
    - newApplication: New Application
    - proxyPath: Proxy path
    - url: URL
- group: management-app-ui
  locale: el
  keys:
    - header: Διαχείριση Εφαρμογών
    - title: Όνομα
    - image: Εικόνα
    - description: Περιγραφή
    - version: Έκδοση
    - cancel: Άκυρο
    - create: Δημιουργία
    - save: Αποθήκευση
    - pagination: Αποτελέσματα ανά σελίδα
    - newApplication: Νέα εφαρμογή
    - proxyPath: Proxy path
    - url: URL
