---
groups:
  - name: webdesktop-ui
    description: webdesktopUi description
  - name: translations-management-ui
    description: translations of translations management application
  - name: management-app-ui
    description: translations of management applications
  - name: user-profile-management-ui
    description: translations of user profile management application
languages:
- name: "English"
  locale: "en"
- name: "Ελληνικά"
  locale: "el"
- name: "Deutsch"
  locale: "de"
- name: "Français"
  locale: "fr"

translations:
- group: webdesktop-ui
  locale: en
  keys:
    - groupOthers: Others
    - system: System
- group: webdesktop-ui
  locale: el
  keys:
    - groupOthers: Άλλα
    - system: Σύστημα

- group: translations-management-ui
  locale: en
  keys:
    - languages: Languages
    - translations: Translations
    - copyTranslations: Copy translations
    - back: Back
    - saveChanges: Save changes
    - groupName: Group Name
    - keyName: Key Name
    - create: Create
    - keyEdit: Key Edit
    - save: Save
    - itemsPerPage: Items per page
    - rangeLabel: of
    - changes: Changes
    - saved: Saved!
    - error: Error!
    - errorMessage: Something went wrong
    - inactive-active: Inactive/Active
    - languageCreate: Language create
    - languageName: Language name
    - languageLocale: Language locale
    - none: None
- group: translations-management-ui
  locale: el
  keys:
    - languages: Γλώσσες
    - translations: Μεταφράσεις
    - copyTranslations: Aντιγράψτε μεταφράσεις
    - back: Επιστροφή
    - saveChanges: Αποθηκεύστε  τις αλλαγές
    - groupName: Όνομα ομάδας
    - keyName: Όνομα κλειδιού
    - create: Δημιουργία
    - keyEdit: Επεξεργασία κλειδιού
    - save: Αποθήκευση
    - itemsPerPage: Aντικείμενα ανά σελίδα
    - rangeLabel: από
    - changes: Οι αλλαγές
    - saved: Αποθηκεύτηκαν
    - error: Σφάλμα!
    - errorMessage: Κάτι πήγε στραβά
    - inactive-active: Ανενεργή/Ενεργή
    - languageCreate: Δημιουργία γλώσσας
    - languageName: Όνομα  γλώσσας
    - languageLocale: Locale γλώσσας
    - none: Καμία
- group: management-app-ui
  locale: en
  keys:
    - header: Applications Management
    - title: Name
    - icon: Image
    - description: Description
    - version: Version
    - cancel: Cancel
    - create: Create
    - save: Save
    - pagination: Items per page
    - newApplication: New Application
    - editApplication: Edit Application
    - proxyPath: Proxy Path
    - appIndex: Application Index
    - iconSmall: Icon Small
    - width: Width
    - minWidth: Min Width
    - height: Height
    - minHeight: Min Height
    - addedOn: Added On
    - lastDeployedOn: Last Deployed On
    - groupName: Group Name
    - applicationName: Application Name
    - multipleInstances: Multiple Instances
    - resizable: Resizable
    - minimizable: Minimizable
    - closable: Closable
    - draggable: Draggable
    - system: System
    - showTitle: Show Title
    - active: Active
    - restrictAccess: Restrict Access
    - newApp: New Application
    - editApp: Edit Application
    - tableDescription: Applications List
    - properties: Properties
    - error: Error
    - dismiss: Dismiss
    - success: Success
    - systemApp: System Applications
    - applications: Applications
    - users: Users
    - upload: Upload
    - uniqueMessage: Must be unique
    - submit: Submit

- group: management-app-ui
  locale: el
  keys:
    - header: Διαχείριση Εφαρμογών
    - title: Όνομα
    - icon: Εικόνα
    - description: Περιγραφή
    - version: Έκδοση
    - cancel: Άκυρο
    - create: Δημιουργία
    - save: Αποθήκευση
    - pagination: Αποτελέσματα ανά σελίδα
    - newApplication: Νέα εφαρμογή
    - editApplication: Επεξεργασία εφαρμογής
    - proxyPath: Proxy Path
    - appIndex: Διαδρομή εφαρμογής
    - iconSmall: Μικρή εικόνα
    - width: Μήκος
    - minWidth: Ελάχιστο μήκος
    - height: Ύψος
    - minHeight: Ελάχιστο ύψος
    - addedOn: Προστέθηκε
    - lastDeployedOn: Τελευταία επεξεργασία
    - groupName: Όνομα ομάδας
    - applicationName: Όνομα εφαρμογής
    - multipleInstances: Πολλαπλά παράθυρα
    - resizable: Αλλαγή διαστάσεων
    - minimizable: Ελαχιστοποίηση
    - closable: Κλεινόμενο
    - draggable: Συρόμενο
    - system: Σύστημα
    - showTitle: Εμφάνιση τίτλου
    - active: Ενεργό
    - restrictAccess: Περιορισμένη πρόσβαση
    - newApp: Νέα εφαρμογή
    - editApp: Επεξεργασία εφαρμογής
    - tableDescription: Λίστα εφαρμογών
    - properties: Ιδιότητες
    - error: Σφάλμα
    - dismiss: Κλείσιμο
    - success: Επιτυχία
    - systemApp: Εφαρμογές Συστήματος
    - applications: Εφαρμογές
    - users: Χρήστες
    - upload: Εισαγωγή αρχείου
    - uniqueMessage: Πρέπει να είναι μοναδικό
    - submit: Υποβολή
    - Min.wdApplicationDTO.minWidth: Πρέπει να είναι μεγαλύτερο/ίσο του 50
    - Min.wdApplicationDTO.width: Πρέπει να είναι μεγαλύτερο/ίσο του 50
    - Min.wdApplicationDTO.minHeight: Πρέπει να είναι μεγαλύτερο/ίσο του 50
    - Min.wdApplicationDTO.height: Πρέπει να είναι μεγαλύτερο/ίσο του 50
    - NotNull.wdApplicationDTO.version: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationDTO.proxyPath: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationDTO.appIndex: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationDTO.icon: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationDTO.iconSmall: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationDTO.applicationName: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationDTO.title: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationDTO.description: Δεν μπορεί να είναι κενό

- group: user-profile-management-ui
  locale: en
  keys:
    - firstName: First Name
    - lastName: Last Name
    - defaultLanguage: Default Language
    - profilePicture: Profile Picture
    - backgroundImage: Background Image
    - save: Save

- group: user-profile-management-ui
  locale: el
  keys:
    - firstName: Όνομα
    - lastName: Επώνυμο
    - defaultLanguage: Προεπιλεγμένη γλώσσα
    - profilePicture: Εικόνα προφίλ
    - backgroundImage: Εικόνα φόντου
    - save: Αποθήκευση
