---
groups:
  - name: webdesktop-ui
    description: webdesktopUi description
  - name: translations-management-ui
    description: translations management description
languages:
- name: "English"
  locale: "en"
- name: "Ελληνικά"
  locale: "el"
- name: "Deutsch"
  locale: "de"
- name: "Français"
  locale: "fr"

translations:
- group: webdesktop-ui
  locale: en
  keys:
    - groupOthers: Others
    - system: System
- group: webdesktop-ui
  locale: el
  keys:
    - groupOthers: Άλλα
    - system: Σύστημα

- group: translations-management-ui
  locale: en
  keys:
    - header: Translations Management
    - languages: Languages
    - translations: Translations
    - cancel: Cancel
    - saveChanges: Save changes
    - groupName: Group Name
    - keyName: Key Name
    - create: Create
    - keyEdit: Key Edit
    - keyCreate: Key Create
    - save: Save
- group: translations-management-ui
  locale: el
  keys:
    - header: Διαχείριση Μεταφράσεων
    - languages: Γλώσσες
    - translations: Μεταφράσεις
    - cancel: Ακύρωση
    - saveChanges: Αποθηκεύστε  τις αλλαγές
    - groupName: Όνομα ομάδας
    - keyName: Όνομα κλειδιού
    - create: Δημιουργία
    - keyEdit: Επεξεργασία κλειδιού
    - keyCreate: Δημιουργία κλειδιού
    - save: Αποθήκευση