---
groups:
  - name: webdesktop-ui
    description: webdesktopUi description
  - name: translations-management-ui
    description: translations of translations management application
  - name: management-app-ui
    description: translations of management applications
  - name: user-profile-management-ui
    description: translations of user profile management application
languages:
- name: "English"
  locale: "en"
- name: "Ελληνικά"
  locale: "el"
- name: "Deutsch"
  locale: "de"
- name: "Français"
  locale: "fr"

translations:
- group: webdesktop-ui
  locale: en
  keys:
    - groupOthers: Others
    - system: System
    - pageNotFound: Page not found
    - errorPageMessage: It looks like you are trying to access a page which does not exist.
    - ContantAdminMessage: Please contant your administrator.
    - Back: BACK
    - profile: Profile
    - logout: Logout
    - minimize: Minimize
    - fullscreen: Fullscreen
    - exitFullscreen: Exit Fullscreen
    - close: Close
- group: webdesktop-ui
  locale: el
  keys:
    - groupOthers: Άλλα
    - system: Σύστημα
    - pageNotFound: Η σελίδα δεν βρέθηκε
    - errorPageMessage: Φαίνεται ότι προσπαθείτε να αποκτήσετε πρόσβαση σε μια σελίδα που δεν υπάρχει.
    - ContantAdminMessage: Επικοινωνήστε με τον διαχειριστή σας.
    - Back: ΕΠΙΣΤΡΟΦΉ
    - profile: Προφίλ
    - logout: Αποσύνδεση
    - minimize: Ελαχιστοποίηση
    - fullscreen: Πλήρης οθόνη
    - exitFullscreen: Έξοδος απο πλήρη οθόνη
    - close: Κλείσιμο
- group: translations-management-ui
  locale: en
  keys:
    - languages: Languages
    - translations: Translations
    - copyTranslations: Copy translations
    - back: Back
    - saveChanges: Save changes
    - groupName: Group Name
    - keyName: Key Name
    - create: Create
    - keyEdit: Key Edit
    - save: Save
    - itemsPerPage: Items per page
    - rangeLabel: of
    - saved: Saved!
    - error: Something went wrong!
    - inactive-active: Inactive/Active
    - languageCreate: Language create
    - languageName: Language name
    - languageLocale: Language locale
    - none: None
    - tabTitle: Translations Management
- group: translations-management-ui
  locale: el
  keys:
    - languages: Γλώσσες
    - translations: Μεταφράσεις
    - copyTranslations: Aντιγράψτε μεταφράσεις
    - back: Επιστροφή
    - saveChanges: Αποθηκεύστε  τις αλλαγές
    - groupName: Όνομα ομάδας
    - keyName: Όνομα κλειδιού
    - create: Δημιουργία
    - keyEdit: Επεξεργασία κλειδιού
    - save: Αποθήκευση
    - itemsPerPage: Aντικείμενα ανά σελίδα
    - rangeLabel: από
    - saved: Αποθηκεύτηκαν
    - error: Κάτι πήγε στραβά!
    - inactive-active: Ανενεργή/Ενεργή
    - languageCreate: Δημιουργία γλώσσας
    - languageName: Όνομα  γλώσσας
    - languageLocale: Locale γλώσσας
    - none: Καμία
    - tabTitle: Διαχείρηση Μεταφράσεων
- group: management-app-ui
  locale: en
  keys:
    - header: Applications Management
    - title: Name
    - icon: Image
    - description: Description
    - version: Version
    - cancel: Cancel
    - create: Create
    - save: Save
    - pagination: Items per page
    - proxyPath: Proxy Path
    - appUrl: Application Url
    - iconSmall: Icon Small
    - width: Width
    - minWidth: Min Width
    - height: Height
    - minHeight: Min Height
    - addedOn: Added On
    - lastDeployedOn: Last Deployed On
    - groupName: Group Name
    - applicationName: Application Name
    - multipleInstances: Multiple Instances
    - resizable: Resizable
    - minimizable: Minimizable
    - closable: Closable
    - draggable: Draggable
    - system: System
    - showTitle: Show Title
    - active: Active
    - restrictAccess: Restrict Access
    - newApp: New Application
    - editApp: Edit Application
    - tableDescription: Applications List
    - properties: Properties
    - error: Error
    - dismiss: Dismiss
    - success: Success
    - systemApp: System Applications
    - applications: Applications
    - users: Users
    - upload: Upload
    - uniqueMessage: Must be unique
    - submit: Submit
    - proxyAppUrl: Proxy Application Url
    - alreadyExistsCode: already exists
    - the: The
    - delete: Delete
    - deleteGroup: Delete Group
    - deleteQuestion: Do you really want to delete this group?
    - groups: Groups
    - created: Group successfully created
    - updated: Group successfully updated
    - deleteSuccess: Group successfully deleted
    - newGroup: New Group
    - editGroup: Edit Group
    - profilePicture: Profile Picture
    - firstName: First Name
    - lastName: Last Name
    - add: Add
    - search: Search
    - notFound: Νot found
    - userName: Username
    - editUser: User edit
    - permissions: Permissions
    - back: Back
    - tabTitle: Applications/Users Management
- group: management-app-ui
  locale: el
  keys:
    - header: Διαχείριση Εφαρμογών
    - title: Όνομα
    - icon: Εικόνα
    - description: Περιγραφή
    - version: Έκδοση
    - cancel: Άκυρο
    - create: Δημιουργία
    - save: Αποθήκευση
    - pagination: Αποτελέσματα ανά σελίδα
    - proxyPath: Proxy Path
    - appUrl: Διαδρομή εφαρμογής
    - iconSmall: Μικρή εικόνα
    - width: Μήκος
    - minWidth: Ελάχιστο μήκος
    - height: Ύψος
    - minHeight: Ελάχιστο ύψος
    - addedOn: Προστέθηκε
    - lastDeployedOn: Τελευταία επεξεργασία
    - groupName: Όνομα ομάδας
    - applicationName: Όνομα εφαρμογής
    - multipleInstances: Πολλαπλά παράθυρα
    - resizable: Αλλαγή διαστάσεων
    - minimizable: Ελαχιστοποίηση
    - closable: Κλεινόμενο
    - draggable: Συρόμενο
    - system: Σύστημα
    - showTitle: Εμφάνιση τίτλου
    - active: Ενεργό
    - restrictAccess: Περιορισμένη πρόσβαση
    - newApp: Νέα εφαρμογή
    - editApp: Επεξεργασία εφαρμογής
    - tableDescription: Λίστα εφαρμογών
    - properties: Ιδιότητες
    - error: Σφάλμα
    - dismiss: Κλείσιμο
    - success: Επιτυχία
    - systemApp: Εφαρμογές Συστήματος
    - applications: Εφαρμογές
    - users: Χρήστες
    - upload: Εισαγωγή αρχείου
    - uniqueMessage: Πρέπει να είναι μοναδικό
    - submit: Υποβολή
    - Min.wdApplicationManagementDTO.minWidth: Πρέπει να είναι μεγαλύτερο/ίσο του 50
    - Min.wdApplicationManagementDTO.width: Πρέπει να είναι μεγαλύτερο/ίσο του 50
    - Min.wdApplicationManagementDTO.minHeight: Πρέπει να είναι μεγαλύτερο/ίσο του 50
    - Min.wdApplicationManagementDTO.height: Πρέπει να είναι μεγαλύτερο/ίσο του 50
    - NotNull.wdApplicationManagementDTO.version: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationManagementDTO.proxyPath: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationManagementDTO.appIndex: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationManagementDTO.icon: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationManagementDTO.iconSmall: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationManagementDTO.applicationName: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationManagementDTO.title: Δεν μπορεί να είναι κενό
    - NotNull.wdApplicationManagementDTO.description: Δεν μπορεί να είναι κενό
    - proxyAppUrl: Proxy Application Url
    - alreadyExistsCode: υπάρχει ήδη
    - the: Το
    - delete: Διαγραφή
    - deleteGroup: Διαγραφή Ομάδας
    - deleteQuestion: Θέλετε σίγουρα να διαγράψετε την ομάδα?
    - groups: Ομάδες
    - created: Επιτυχής δημιουργία
    - updated: Επιτυχής ενημέρωση
    - deleteSuccess: Επιτυχής διαγραφή
    - newGroup: Νέα ομάδα
    - editGroup: Επεξεργασία ομάδας
    - profilePicture: Εικόνα προφίλ
    - firstName: Όνομα
    - lastName: Επίθετο
    - add: Προσθήκη
    - search: Αναζήτηση
    - notFound: Δεν βρέθηκε
    - userName: Όνομα χρήστη
    - editUser: Επεξεργασία χρήστη
    - permissions: Δικαιώματα
    - NotNull.userGroupManagementDTO.userGroupName: Δεν μπορεί να είναι κενό
    - back: Επιστροφή
    - tabTitle: Διαχείρηση Εφαρμογών/Χρηστών
- group: user-profile-management-ui
  locale: en
  keys:
    - firstName: First Name
    - lastName: Last Name
    - defaultLanguage: Default Language
    - profilePicture: Profile Picture
    - backgroundImage: Background Image
    - save: Save
    - tabTitle: User Profile Management
    - saved: Saved!
    - error: Something went wrong!
- group: user-profile-management-ui
  locale: el
  keys:
    - firstName: Όνομα
    - lastName: Επώνυμο
    - defaultLanguage: Προεπιλεγμένη γλώσσα
    - profilePicture: Εικόνα προφίλ
    - backgroundImage: Εικόνα φόντου
    - save: Αποθήκευση
    - tabTitle: Διαχείρηση Προφίλ Χρήστη
    - saved: Αποθηκεύτηκαν
    - error: Κάτι πήγε στραβά!