---
groups:
  - name: webdesktop-ui
    description: webdesktopUi description

languages:
- name: "English"
  locale: "en"
- name: "Ελληνικά"
  locale: "el"
- name: "Deutsch"
  locale: "de"
- name: "français"
  locale: "fr"

translations:
- group: webdesktop-ui
  locale: en
  keys:
    - groupOthers: Others
- group: webdesktop-ui
  locale: el
  keys:
    - groupOthers: Άλλα

