---
groups:
  - name: webdesktop-ui
    description: webdesktopUi  description
languages:
- name: "English"
  locale: "en"
- name: "Greek"
  locale: "el"
translations:
- group: webdesktop-ui
  locale: en
  keys:
   - group1: Group 1
   - group2: Group 2
   - group3: Group 3
   - group4: Group 4
- group: webdesktop-ui
  locale: el
  keys:
  - group1: ομάδα  1
  - group2: ομάδα  2
  - group3: ομάδα  3
  - group4: ομάδα  4

