# application configuration
---
applicationName: Translations Management
groupName: system
appUrl: "http://localhost:8091"
appPath: "/translationsManagement/"
icon: "http://localhost:8082/translationsManagement/logo/icon"
iconSmall: "http://localhost:8082/translationsManagement/logo/icon_small"
width: "800"
minWidth: "470"
height: "500"
minHeight: "450"
active: true
multipleInstances: false
restrictAccess: false
resizable: true
draggable: true
closable: true
minimizable: true
maximizable: true
system: true
showTitle: true
proxyAppPath: "/translationsManagement/"
version: "3.0.0-SNAPSHOT"
lexicon:
  - languageLocale: en
    values:
      - key: title
        value: Translations Management
      - key: description
        value: System application which manages the translations.
  - languageLocale: el
    values:
      - key: title
        value: Διαχείρηση Μεταφράσεων
      - key: description
        value: Εφαρμογή συστήματος η οποία διαχειρίζεται τις μεταφράσεις.