# application configuration
---
applicationName: User Profile Management
groupName: system
appUrl: "http://qlack-webdesktop-user-profile-management:8092"
appPath: "/userProfileManagement/"
proxyAppPath: "/userProfileManagement/"
icon: "/userProfileManagement/logo/icon"
iconSmall: "/userProfileManagement/logo/icon_small"
width: "800"
minWidth: "470"
height: "500"
minHeight: "450"
active: true
multipleInstances: false
resizable: true
draggable: true
closable: true
minimizable: true
maximizable: true
showTitle: true
system: false
restrictAccess: false
version: "3.0.0-SNAPSHOT"
lexicon:
  - languageLocale: en
    values:
      - key: title
        value: User Profile Management
      - key: description
        value: System application which manages the user profile.
  - languageLocale: el
    values:
      - key: title
        value: Διαχείρηση Προφίλ Χρήστη
      - key: description
        value: Εφαρμογή συστήματος η οποία διαχειρίζεται το προφίλ χρήστη.